IF EXISTS (
  SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'Tours'
    AND COLUMN_NAME = 'image'
    AND CHARACTER_MAXIMUM_LENGTH > 0
    AND CHARACTER_MAXIMUM_LENGTH < 2048
)
BEGIN
  ALTER TABLE Tours ALTER COLUMN image NVARCHAR(2048) NULL;
END;
GO

IF EXISTS (
  SELECT 1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'TourActivities'
    AND COLUMN_NAME = 'image'
    AND CHARACTER_MAXIMUM_LENGTH > 0
    AND CHARACTER_MAXIMUM_LENGTH < 2048
)
BEGIN
  ALTER TABLE TourActivities ALTER COLUMN image NVARCHAR(2048) NULL;
END;
GO
